# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kyndor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kyndor
  pod 'AppCenter/Crashes' #, '~> 1.5.0'
  pod 'AppCenter/Analytics' #, '~> 1.5.0'
  pod 'AppCenterReactNativeShared' #, '~> 1.4.0'

  #pod 'React', :path => '../node_modules/react-native'
  #pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  rn_maps_path = '../node_modules/react-native-maps'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'RCTAnimation',
  'RCTBlob',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTActionSheet',
  'RCTGeolocation',
  'RCTSettings',
  'RCTVibration',
  'DevSupport',
  'BatchedBridge',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-maps', path: rn_maps_path
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  #pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'



#platform :ios, '9.0'
  target 'KyndorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Kyndor-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Kyndor-tvOS

  target 'Kyndor-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
